[Menu]
[[Menu.main]]
name = "Home"
url = "/"
weight = 1
[[Menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
[[Menu.main]]
name = "About"
url = "/about/"
weight = 3
[[Menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

